version: '3.8'

services:
  api:
    build: .
    container_name: cesnet-anomaly-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped